export const currencyByRupee: Currency[]=[
    {
        name:'Dollar',
        value:0.014,
        flag:'🇺🇸',
        symbol:'$'
    },
    {
        name:'Euro',
        value:0.012,
        flag:'🇪🇺',
        symbol:'€'
    },
    {
        name:'Pound',
        value:0.011,
        flag:'🇬🇧',
        symbol:'£'
    },
    {
        name:'Yen',
        value:1.54,
        flag:'🇯🇵',
        symbol:'¥'
    },
    {
        name:'Yuan',
        value:0.091,
        flag:'🇨🇳',
        symbol:'¥'
    },
    {
        name:'Dinar',
        value:0.0043,
        flag:'🇰🇼',
        symbol:'د.ك'
    },
    {
        name:'Dirham',
        value:0.051,
        flag:'🇦🇪',
        symbol:'د.إ'
    },
    {
        name:'Ruble',
        value:1.05,
        flag:'🇷🇺',
        symbol:'₽'
    },
    {
        name:'Peso',
        value:0.28,
        flag:'🇲🇽',
        symbol:'$'
    },
    {
        name:'Real',
        value:0.073,
        flag:'🇧🇷',
        symbol:'R$'
    },
    {
        name:'Rupee',
        value:1,
        flag:'🇮🇳',
        symbol:'₹'
    }
]